### ISSUE TITLE
Cannot disable "Code Lens" style overlay over every function in Jetbrains Rider

### ISSUE THREAD

**Issue by wyndn** [Exafunction/CodeiumJetBrains#14]
The lines add up quite a bit in large classes and tend to clutter the page. 
![2024-02-02_01-27](https://github.com/Exafunction/CodeiumJetBrains/assets/53494070/0dab9cfa-6fa9-42f9-87d5-3bb268c7e221)

**Comment by fortenforge** [comment]
You can disable these in the Codeium Settins.
