### ISSUE TITLE
Chinese garbled characters

### ISSUE THREAD

**Issue by maguangzu** [Exafunction/CodeiumJetBrains#19]
When using the default console font in Idea, there is a prompt for garbled Chinese characters, but after pressing the tab key, it is still good

**Comment by fortenforge** [comment]
dupe of https://github.com/Exafunction/CodeiumJetBrains/issues/1

**Comment by maguangzu** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
