### ISSUE TITLE
Clion 2024.2.2 w/ Codeium 1.16.13 through 1.20.2: "Disconnected from Codeium Server", inlay hints broken

### ISSUE THREAD

**Issue by Algomorph** [Exafunction/CodeiumJetBrains#40]
I'm seeing "Disconnected from Codeium Server" on Clion 2024.2.2 w/ Codeium 1.16.13 on the (older?) $15/mo Teams plan.

No combination of uninstalling, deleting `$HOME/.codeium` folder, re-logging in fixes this.
Inlay hints / autocomplete not working. Chat appears to be working. Indexing also appears to be working (sans errors in the log, I suppose).

CLion log:
[idea.log](https://github.com/user-attachments/files/17059957/idea.log)

Codeium diagnostics (from "Download Diagnostics"):
[Codeium_Diagnostics.log](https://github.com/user-attachments/files/17059972/Codeium_Diagnostics.log)

**Comment by Algomorph** [comment]
Also happening in PyCharm:
```
PyCharm 2024.2.1 (Community Edition)
Build #PC-242.21829.153, built on August 29, 2024
Runtime version: 21.0.3+13-b509.11 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-40-generic
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 4096M
Cores: 32
Registry:
  ide.experimental.ui=true
  i18n.locale=
  terminal.new.ui=true
Non-Bundled Plugins:
  com.codeium.intellij (1.16.13)
  com.intellij.plugins.eclipsekeymap (242.20224.204)
  org.jetbrains.plugins.gitlab (242.21829.162)
Current Desktop: ubuntu:GNOME
```

**Comment by mryll** [comment]
I’m experiencing the exact same issue, but on Goland 2024.2.2 (Codeium 1.16.13). I’m on the Pro plan.

**Comment by reallyflying** [comment]
me too，I am using pycharm, Codeium latest version 1.16.13

**Comment by Malakof** [comment]
1.16.18 still broken in pycharm, no completion, going back to 1.14.14

[diags.txt](https://github.com/user-attachments/files/17095121/diags.txt)

**Comment by ZerGo0** [comment]
UPDATE: Codeium 1.20.2 didn't fix it for me.

> 1.16.18 still broken in pycharm, no completion, going back to 1.14.14
> 
> [diags.txt](https://github.com/user-attachments/files/17095121/diags.txt)

Going back to [1.14.14](https://plugins.jetbrains.com/plugin/20540-codeium-ai-autocomplete-and-chat-for-python-js-java-go--/versions/stable/596179) worked for me as well. 1.16.X does not for me either.

1. Download version 1.14.14 from above
2. Open your IDE and press Ctrl+Alt+S to open the IDE settings.
3. Select Plugins, click the cog and then click Install Plugin from Disk.
4. Select the plugin archive file and click OK.
5. Click OK to apply the changes and restart your IDE if prompted.

**Comment by gtache** [comment]
Same problem on IntelliJ Ultimate 2024.2.0.2.      
Going back to 1.14.14 worked for me as well, thanks for the procedure.

**Comment by Algomorph** [comment]
Problem still present w/ Codeium plugin ver 1.20.2

**Comment by fortenforge** [comment]
Can you share your idea.log file?

**Comment by Algomorph** [comment]
@fortenforge here.

All I have to do is hit "enter" in a .cpp file and I get "Disconnected from Codeium Server". So it looks like it tires to do autocomplete, then disconnects right away.

[idea.log](https://github.com/user-attachments/files/17170872/idea.log)

**Comment by Algomorph** [comment]
`1.20.4` fixes the issue! Thank you @fortenforge and any other maintainers who worked on this. Other users: closing, reopen if needed.
