### ISSUE TITLE
Use proxy from IDE settings

### ISSUE THREAD

**Issue by davidmz** [Exafunction/CodeiumJetBrains#9]
It looks like the Codeium plugin does not use the HTTP proxy from the IDE settings. If this is really the case, could you please fix it?

**Comment by fortenforge** [comment]
What error are you seeing to suggest this? Our main plugin frontend should use this HTTP proxy, and the language server binary we spin up tries to determine if it should use a proxy when connecting.

**Comment by davidmz** [comment]
Sorry, it looks like I'm having local network configuration issues. It works as expected now.
